# Matrix Group Work

What are the dimensions of the matrix products A and B defined as in the following A = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],  and B = [[1, 2],[5, 6],[3, 0],[2, 1]] 

In [9]:
import numpy as np
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
B = np.array([[1, 2],[5, 6],[3, 0],[2, 1]] )
print(B)

[[1 2]
 [5 6]
 [3 0]
 [2 1]]


In [11]:
A + B

ValueError: operands could not be broadcast together with shapes (3,4) (4,2) 

In [18]:
print('dimensions of A:', A.shape)
print('dimensions of B:', B.shape)

dimensions of A: (3, 4)
dimensions of B: (4, 2)


In both cases note that dimensions (rows , columns)  are NOT equal.  But the columns of A are the same as the Rows of B.  Good news, WE CANNOT ADD but WE CAN MULTIPLY generalizing the dot product

In [22]:
AB = np.matmul(A,B)
print('AB is the product of AB=')
print(AB)
print('dimensions of AB:', AB.shape)

AB is the product of AB=
[[ 28  18]
 [ 72  54]
 [116  90]]
dimensions of C: (3, 2)
